#you should put here real key, secret and endpoint to write new cassetes and make rspec pass
test:
    access_key: "test_key"
    secret_key: "test_secret"
    wsdl_endpoint: "https://some-url.mktoapi.com/soap/mktows/2_2"
